name: hikairi ollvm


on:
 push:
   branches: [llvm-18.1.8rel]
   
 workflow_dispatch:
   
jobs:
 
 windows:
    name: Build for Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: make diffutils unzip gzip cmake ninja git
          pacboy: 7zip:p python:p cmake:p gcc:p ninja:p zstd:p clang:p lld:p

      - name: Build toolchain
        run: |
         git submodule init 
         git submodule update
         mkdir build
         cd build
         cmake -G "Ninja" -DLLVM_ENABLE_PROJECTS="clang;lld" -DCMAKE_BUILD_TYPE=Release -DLLVM_INCLUDE_TESTS=OFF -DLLVM_ENABLE_NEW_PASS_MANAGER=TRUE ../llvm
         ninja -j12
